export const CITY_INFO = {
    history: `बैतूल जिला मध्यप्रदेश के दक्षिण-पश्चिम में स्थित है। यह जिला 1901 में बनाया गया था और यहाँ की प्राकृतिक सुंदरता, आदिवासी संस्कृति और ऐतिहासिक स्थल इसे विशेष बनाते हैं।

बैतूल का इतिहास बहुत पुराना है। यहाँ सातपुड़ा पर्वत श्रृंखला की गोद में बसे इस क्षेत्र में गोंड राजाओं का शासन रहा है। अंग्रेजी काल में यह एक महत्वपूर्ण प्रशासनिक केंद्र था।

आज बैतूल एक तेजी से विकसित होता शहर है जहाँ शिक्षा, व्यापार और पर्यटन के अच्छे अवसर हैं।`,

    about: 'बैतूल (Betul) मध्यप्रदेश का एक ऐतिहासिक जिला है, जो सातपुड़ा पर्वत श्रृंखला के बीच बसा है। यह अपनी प्राकृतिक सुंदरता और आदिवासी संस्कृति के लिए प्रसिद्ध है।',

    population: '~15 लाख',
    area: '10,043 वर्ग किमी',
    language: 'हिंदी, गोंडी',
    tehsils: ['बैतूल', 'मुलताई', 'भैंसदेही', 'आमला', 'शाहपुर', 'चिचोली', 'प्रभातपट्टन', 'घोड़ाडोंगरी'],
};

export const FAMOUS_PLACES = [
    {
        id: '1',
        name: 'मुक्तागिरि जैन मंदिर',
        category: 'temple',
        emoji: '🛕',
        description: '52 जैन मंदिरों का अद्भुत समूह, प्रकृति की गोद में बसा पवित्र तीर्थस्थल।',
        distance: '45 km',
        rating: 4.8,
        color: '#FF6B35',
    },
    {
        id: '2',
        name: 'ताप्ती नदी उद्गम',
        category: 'nature',
        emoji: '🌊',
        description: 'पवित्र ताप्ती नदी का उद्गम स्थल मुलताई, एक अत्यंत पवित्र स्थान।',
        distance: '50 km',
        rating: 4.5,
        color: '#2196F3',
    },
    {
        id: '3',
        name: 'सारणी बांध',
        category: 'nature',
        emoji: '🏞️',
        description: 'तवा नदी पर बना यह बांध पर्यटन और पिकनिक के लिए आदर्श स्थान है।',
        distance: '30 km',
        rating: 4.3,
        color: '#4CAF50',
    },
    {
        id: '4',
        name: 'भीमकुंड',
        category: 'nature',
        emoji: '💧',
        description: 'रहस्यमयी प्राकृतिक कुंड जिसकी गहराई आज तक अज्ञात है।',
        distance: '55 km',
        rating: 4.6,
        color: '#9C27B0',
    },
    {
        id: '5',
        name: 'पाताल कोट',
        category: 'tourism',
        emoji: '🏔️',
        description: 'घाटी में बसी रहस्यमयी बस्ती, भारिया आदिवासियों का अनोखा संसार।',
        distance: '90 km',
        rating: 4.7,
        color: '#795548',
    },
    {
        id: '6',
        name: 'बैतूल बाजार',
        category: 'market',
        emoji: '🛍️',
        description: 'शहर का मुख्य बाजार, स्थानीय हस्तकला और खरीदारी का केंद्र।',
        distance: '0 km',
        rating: 4.2,
        color: '#FF9800',
    },
];

export const EMERGENCY_CONTACTS = [
    { id: '1', name: 'पुलिस', number: '100', emoji: '🚔', color: '#1565C0' },
    { id: '2', name: 'अग्निशमन', number: '101', emoji: '🚒', color: '#D32F2F' },
    { id: '3', name: 'एम्बुलेंस', number: '108', emoji: '🚑', color: '#388E3C' },
    { id: '4', name: 'जिला अस्पताल', number: '07141-234567', emoji: '🏥', color: '#00838F' },
    { id: '5', name: 'नगर पालिका', number: '07141-245678', emoji: '🏛️', color: '#7B1FA2' },
    { id: '6', name: 'बिजली विभाग', number: '1912', emoji: '⚡', color: '#F57F17' },
    { id: '7', name: 'जल विभाग', number: '07141-256789', emoji: '💧', color: '#0277BD' },
    { id: '8', name: 'महिला हेल्पलाइन', number: '1091', emoji: '👮‍♀️', color: '#AD1457' },
];

// ─────────── LOCAL SHOPS (ADS) DATA ───────────
export const ADS_DATA = [
    {
        id: '1',
        shopName: 'श्री गणेश किराना स्टोर',
        category: 'grocery',
        tagline: 'घर की जरूरत, सबसे सस्ती कीमत',
        offer: '20% OFF on First Order',
        phone: '9876543210',
        whatsapp: '9876543210',
        address: 'मेन मार्केट, बैतूल',
        plan: 'homepage',
        badge: '💎 Featured',
        color: '#FF6B35',
        rating: 4.5,
        reviews: 128,
        openTime: 'सुबह 7:00 – रात 10:00',
        isOpen: true,
        tags: ['किराना', 'Daily needs', 'Home delivery'],
    },
    {
        id: '2',
        shopName: 'Fashion Hub Betul',
        category: 'clothing',
        tagline: 'Latest Fashion at Best Price',
        offer: 'Buy 2 Get 1 Free',
        phone: '9876543211',
        whatsapp: '9876543211',
        address: 'स्टेशन रोड, बैतूल',
        plan: 'homepage',
        badge: '🔥 ट्रेंडिंग',
        color: '#E91E63',
        rating: 4.2,
        reviews: 89,
        openTime: 'सुबह 10:00 – रात 9:00',
        isOpen: true,
        tags: ['कपड़े', 'Fashion', 'Ladies', 'Kids'],
    },
    {
        id: '3',
        shopName: 'Tech World Betul',
        category: 'electronics',
        tagline: 'सभी Electronics सबसे कम दाम पर',
        offer: 'EMI @0% on all Products',
        phone: '9876543212',
        whatsapp: '9876543212',
        address: 'कॉलेज रोड, बैतूल',
        plan: 'homepage',
        badge: '⭐ Premium',
        color: '#1976D2',
        rating: 4.7,
        reviews: 213,
        openTime: 'सुबह 10:00 – रात 8:30',
        isOpen: true,
        tags: ['Mobile', 'Laptop', 'Repair', 'Accessories'],
    },
    {
        id: '4',
        shopName: 'साईं मेडिकल स्टोर',
        category: 'medical',
        tagline: '24x7 दवाइयाँ और स्वास्थ्य उत्पाद',
        offer: '10% OFF on all Medicines',
        phone: '9876543213',
        whatsapp: '9876543213',
        address: 'हॉस्पिटल रोड, बैतूल',
        plan: 'standard',
        badge: '💊 24/7 Open',
        color: '#43A047',
        rating: 4.6,
        reviews: 176,
        openTime: '24 घंटे खुला',
        isOpen: true,
        tags: ['दवाई', 'Generic', 'Vitamins', '24/7'],
    },
    {
        id: '5',
        shopName: 'बैतूल स्वीट्स & बेकरी',
        category: 'food',
        tagline: 'ताजी मिठाई और बेकरी आइटम',
        offer: 'Order 500g+ पर Free Delivery',
        phone: '9876543214',
        whatsapp: '9876543214',
        address: 'घंटाघर चौक, बैतूल',
        plan: 'standard',
        badge: '🍬 Fresh Daily',
        color: '#FF9800',
        rating: 4.4,
        reviews: 94,
        openTime: 'सुबह 6:00 – रात 10:00',
        isOpen: true,
        tags: ['मिठाई', 'Cake', 'Namkeen', 'ताजा'],
    },
    {
        id: '6',
        shopName: 'Betul Auto Garage',
        category: 'services',
        tagline: 'All Vehicles Repair & Service',
        offer: 'Free AC Check with any Service',
        phone: '9876543215',
        whatsapp: '9876543215',
        address: 'NH-69, नजदीक बस स्टैंड, बैतूल',
        plan: 'standard',
        badge: '🔧 Trusted',
        color: '#607D8B',
        rating: 4.3,
        reviews: 65,
        openTime: 'सुबह 8:00 – शाम 7:00',
        isOpen: false,
        tags: ['Car', 'Bike', 'AC', 'Repair'],
    },
    {
        id: '7',
        shopName: 'Akash Stationery & Books',
        category: 'education',
        tagline: 'सभी Books, Stationery & Gifts',
        offer: 'School Books पर 15% Discount',
        phone: '9876543216',
        whatsapp: '9876543216',
        address: 'स्कूल रोड, बैतूल',
        plan: 'basic',
        badge: '📚 Education',
        color: '#7B1FA2',
        rating: 4.1,
        reviews: 42,
        openTime: 'सुबह 9:00 – शाम 8:00',
        isOpen: true,
        tags: ['Books', 'Stationery', 'Gifts', 'School'],
    },
    {
        id: '8',
        shopName: 'रामजी सैलून & Spa',
        category: 'services',
        tagline: 'Premium Gents Salon & Grooming',
        offer: 'Haircut + Beard Free ₹99 only',
        phone: '9876543217',
        whatsapp: '9876543217',
        address: 'लखनपुर रोड, बैतूल',
        plan: 'basic',
        badge: '✂️ Premium',
        color: '#00BCD4',
        rating: 4.0,
        reviews: 38,
        openTime: 'सुबह 9:00 – रात 9:00',
        isOpen: true,
        tags: ['Salon', 'Haircut', 'Beard', 'Grooming'],
    },
];

// ─────────── MARKETPLACE LISTINGS ───────────
export const MARKETPLACE_LISTINGS = [
    {
        id: '1',
        title: 'Honda Activa 5G - 2021',
        price: 65000,
        category: 'bikes',
        emoji: '🏍️',
        description: 'बहुत अच्छी condition में, single owner, all papers clear. 22,000 km driven only. Insurance valid till 2025.',
        location: 'बैतूल शहर',
        postedBy: 'Rahul Sharma',
        phone: '9876543210',
        whatsapp: '9876543210',
        timeAgo: '2 घंटे पहले',
        isVerified: true,
        views: 142,
        condition: 'Excellent',
    },
    {
        id: '2',
        title: 'Samsung Galaxy S21 - 128GB',
        price: 28000,
        category: 'electronics',
        emoji: '📱',
        description: 'Box pack condition, 6 months warranty remaining, charger & earphones included. No scratches.',
        location: 'मुलताई',
        postedBy: 'Priya Patel',
        phone: '9876543211',
        whatsapp: '9876543211',
        timeAgo: '5 घंटे पहले',
        isVerified: false,
        views: 89,
        condition: 'Like New',
    },
    {
        id: '3',
        title: '3BHK Flat for Rent',
        price: 8000,
        category: 'realestate',
        emoji: '🏠',
        description: 'नया flat, सभी सुविधाएं, road से 100 meter. 1st floor, 24x7 water & electricity. Monthly rent.',
        location: 'कॉलेज रोड, बैतूल',
        postedBy: 'Suresh Kumar',
        phone: '9876543212',
        whatsapp: '9876543212',
        timeAgo: '1 दिन पहले',
        isVerified: true,
        views: 234,
        condition: 'New',
    },
    {
        id: '4',
        title: 'Office Furniture Set',
        price: 15000,
        category: 'furniture',
        emoji: '🪑',
        description: '5 chairs + 1 table, good condition, price negotiable. Teakwood material. 2 years old.',
        location: 'बैतूल',
        postedBy: 'Anita Singh',
        phone: '9876543213',
        whatsapp: '9876543213',
        timeAgo: '2 दिन पहले',
        isVerified: false,
        views: 56,
        condition: 'Good',
    },
    {
        id: '5',
        title: 'Computer Operator – बैतूल',
        price: 0,
        category: 'jobs',
        emoji: '💼',
        description: 'MS Office proficiency required. Tally knowledge preferred. Salary: ₹10,000–₹15,000/month. Apply in person with CV.',
        location: 'बैतूल शहर',
        postedBy: 'Betul Info Tech',
        phone: '9876540001',
        whatsapp: '9876540001',
        timeAgo: '3 घंटे पहले',
        isVerified: true,
        views: 312,
        condition: 'N/A',
    },
    {
        id: '6',
        title: 'Tata Nexon 2020 – Petrol',
        price: 850000,
        category: 'bikes',
        emoji: '🚗',
        description: 'Single owner, full insurance 2025, original keys & service book, clean record. 45,000 km driven.',
        location: 'आमला',
        postedBy: 'Vikram Rao',
        phone: '9876540002',
        whatsapp: '9876540002',
        timeAgo: '4 घंटे पहले',
        isVerified: false,
        views: 178,
        condition: 'Very Good',
    },
    {
        id: '7',
        title: 'LG 1.5 Ton Split AC – 2022',
        price: 22000,
        category: 'electronics',
        emoji: '❄️',
        description: '3-star rating, inverter AC, with installation kit. Working perfectly. Selling due to relocation.',
        location: 'बैतूल',
        postedBy: 'Deepak Joshi',
        phone: '9876540003',
        whatsapp: '9876540003',
        timeAgo: '6 घंटे पहले',
        isVerified: true,
        views: 93,
        condition: 'Good',
    },
    {
        id: '8',
        title: 'Shop Space for Rent – 250 sqft',
        price: 5000,
        category: 'realestate',
        emoji: '🏪',
        description: 'Main market location, ground floor, high footfall area. Ideal for retail/salon/medical. Monthly rent.',
        location: 'घंटाघर, बैतूल',
        postedBy: 'Rajesh Verma',
        phone: '9876540004',
        whatsapp: '9876540004',
        timeAgo: '12 घंटे पहले',
        isVerified: true,
        views: 421,
        condition: 'N/A',
    },
];

// ─────────── ESSENTIALS PRODUCTS ───────────
export const ESSENTIALS_PRODUCTS = [
    // Morning Breakfast
    { id: '1', name: 'अंडे', nameEn: 'Eggs', emoji: '🥚', price: 8, unit: 'प्रति अंडा', category: 'morning', color: '#FF9800', description: 'ताजे देसी अंडे, प्रतिदिन सुबह डिलीवरी', discount: 0, isOrganic: true },
    { id: '2', name: 'डबल रोटी', nameEn: 'Bread', emoji: '🍞', price: 35, unit: 'प्रति पैकेट', category: 'morning', color: '#795548', description: 'Fresh ब्राउन ब्रेड, सुबह 7 बजे तक', discount: 0, isOrganic: false },
    { id: '3', name: 'समोसे', nameEn: 'Samosa', emoji: '🥟', price: 15, unit: 'प्रति पीस', category: 'morning', color: '#FF6B35', description: 'गरमागरम समोसे, हर सुबह ताजे बने', discount: 10, isOrganic: false },
    { id: '4', name: 'जलेबी', nameEn: 'Jalebi', emoji: '🍮', price: 120, unit: 'प्रति किलो', category: 'morning', color: '#FF9800', description: 'मीठी और कुरकुरी जलेबी, घर पर बनी', discount: 0, isOrganic: false },
    { id: '5', name: 'पोहा', nameEn: 'Poha', emoji: '🌾', price: 30, unit: 'प्रति पैकेट', category: 'morning', color: '#FFCC02', description: 'Ready-to-eat ताजा पोहा, बैतूल style', discount: 15, isOrganic: false },
    { id: '6', name: 'इडली-सांभर', nameEn: 'Idli Sambar', emoji: '🍱', price: 50, unit: 'per plate', category: 'morning', color: '#43A047', description: '4 इडली + सांभर + चटनी, हर सुबह', discount: 0, isOrganic: false },

    // Dairy
    { id: '7', name: 'दूध', nameEn: 'Milk', emoji: '🥛', price: 55, unit: 'प्रति लीटर', category: 'dairy', color: '#90CAF9', description: 'शुद्ध डेयरी दूध, रोजाना सुबह', discount: 0, isOrganic: true },
    { id: '8', name: 'दही', nameEn: 'Curd', emoji: '🍶', price: 60, unit: 'प्रति 500g', category: 'dairy', color: '#FFFFFF', description: 'ताजा घर जैसा दही, प्रतिदिन', discount: 5, isOrganic: true },
    { id: '9', name: 'पनीर', nameEn: 'Paneer', emoji: '🧀', price: 90, unit: 'प्रति 200g', category: 'dairy', color: '#FFF9C4', description: 'ताजा मुलाम पनीर, रोज बना', discount: 0, isOrganic: false },
    { id: '10', name: 'मक्खन', nameEn: 'Butter', emoji: '🧈', price: 55, unit: 'प्रति 100g', category: 'dairy', color: '#FFEB3B', description: 'शुद्ध सफेद मक्खन, घर का बना', discount: 0, isOrganic: true },
    { id: '11', name: 'घी', nameEn: 'Ghee', emoji: '🫙', price: 200, unit: 'प्रति 250g', category: 'dairy', color: '#FF9800', description: 'देसी गाय का घी, शुद्ध और ताजा', discount: 10, isOrganic: true },
    { id: '12', name: 'लस्सी', nameEn: 'Lassi', emoji: '🥤', price: 25, unit: 'per glass', category: 'dairy', color: '#FFECB3', description: 'ठंडी मीठी लस्सी, दिन में ताजगी', discount: 0, isOrganic: false },

    // Vegetables
    { id: '13', name: 'आलू', nameEn: 'Potato', emoji: '🥔', price: 30, unit: 'प्रति किलो', category: 'vegetables', color: '#8BC34A', description: 'ताजे आलू, खेत से सीधे', discount: 0, isOrganic: false },
    { id: '14', name: 'प्याज', nameEn: 'Onion', emoji: '🧅', price: 25, unit: 'प्रति किलो', category: 'vegetables', color: '#CE93D8', description: 'देसी लाल प्याज, तीखे और ताजे', discount: 0, isOrganic: false },
    { id: '15', name: 'टमाटर', nameEn: 'Tomato', emoji: '🍅', price: 35, unit: 'प्रति किलो', category: 'vegetables', color: '#F44336', description: 'लाल और ताजे टमाटर', discount: 0, isOrganic: true },
    { id: '16', name: 'पत्ता गोभी', nameEn: 'Cabbage', emoji: '🥬', price: 25, unit: 'प्रति किलो', category: 'vegetables', color: '#4CAF50', description: 'हरी और ताजी पत्ता गोभी', discount: 0, isOrganic: false },
    { id: '17', name: 'लहसुन', nameEn: 'Garlic', emoji: '🧄', price: 80, unit: 'प्रति 250g', category: 'vegetables', color: '#E0E0E0', description: 'देसी लहसुन, खुशबूदार', discount: 0, isOrganic: true },
    { id: '18', name: 'हरी मिर्च', nameEn: 'Green Chili', emoji: '🌶️', price: 15, unit: 'प्रति 100g', category: 'vegetables', color: '#4CAF50', description: 'तीखी हरी मिर्च, ताजी', discount: 0, isOrganic: false },

    // Fruits
    { id: '19', name: 'केला', nameEn: 'Banana', emoji: '🍌', price: 40, unit: 'per dozen', category: 'fruits', color: '#FFEB3B', description: 'पके और मीठे केले', discount: 0, isOrganic: false },
    { id: '20', name: 'सेब', nameEn: 'Apple', emoji: '🍎', price: 150, unit: 'प्रति किलो', category: 'fruits', color: '#F44336', description: 'कश्मीरी सेब, मीठे और कुरकुरे', discount: 5, isOrganic: false },
    { id: '21', name: 'अमरूद', nameEn: 'Guava', emoji: '🍈', price: 40, unit: 'प्रति किलो', category: 'fruits', color: '#A5D6A7', description: 'ताजा अमरूद, मीठा और ताजा', discount: 0, isOrganic: true },
    { id: '22', name: 'संतरा', nameEn: 'Orange', emoji: '🍊', price: 60, unit: 'प्रति किलो', category: 'fruits', color: '#FF9800', description: 'नागपुरी संतरे, रसीले और ताजे', discount: 10, isOrganic: false },

    // Snacks
    { id: '23', name: 'नमकीन', nameEn: 'Namkeen', emoji: '🫘', price: 50, unit: 'per 200g pack', category: 'snacks', color: '#FF6B35', description: 'बैतूल की मशहूर नमकीन', discount: 0, isOrganic: false },
    { id: '24', name: 'बिस्किट', nameEn: 'Biscuits', emoji: '🍪', price: 20, unit: 'per pack', category: 'snacks', color: '#8D6E63', description: 'ताजे क्रिस्पी बिस्किट', discount: 0, isOrganic: false },
    { id: '25', name: 'चकली', nameEn: 'Chakli', emoji: '🌀', price: 120, unit: 'per 300g', category: 'snacks', color: '#FF9800', description: 'घर जैसी कुरकुरी चकली', discount: 0, isOrganic: false },
    { id: '26', name: 'चाय पत्ती', nameEn: 'Tea', emoji: '🍵', price: 80, unit: 'per 100g', category: 'snacks', color: '#795548', description: 'असम की शुद्ध चाय पत्ती', discount: 0, isOrganic: false },
];

export const HOME_CATEGORIES = [
    { id: '1', name: 'City Info', nameHi: 'शहर की जानकारी', emoji: '🏙️', screen: 'CityInfo', color: '#1976D2' },
    { id: '2', name: 'Ads', nameHi: 'विज्ञापन', emoji: '📢', screen: 'Ads', color: '#FF6B35' },
    { id: '3', name: 'Marketplace', nameHi: 'बाज़ार', emoji: '🛍️', screen: 'Marketplace', color: '#9C27B0' },
    { id: '4', name: 'Essentials', nameHi: 'दैनिक जरूरत', emoji: '🌅', screen: 'Essentials', color: '#4CAF50' },
    { id: '5', name: 'Emergency', nameHi: 'आपातकाल', emoji: '🆘', screen: 'Emergency', color: '#F44336' },
    { id: '6', name: 'Famous Places', nameHi: 'प्रसिद्ध स्थान', emoji: '🗺️', screen: 'FamousPlaces', color: '#FF9800' },
];

export const BANNER_DATA = [
    {
        id: '1',
        title: 'Betul Festival Sale',
        subtitle: 'सभी दुकानों पर भारी छूट',
        gradient: ['#FF6B35', '#FF8C5A'],
        emoji: '🎉',
    },
    {
        id: '2',
        title: 'Fresh Morning Delivery',
        subtitle: 'अंडा, रोटी, दूध - सुबह 7 बजे तक',
        gradient: ['#1A1A2E', '#16213E'],
        emoji: '🌅',
    },
    {
        id: '3',
        title: 'Sell Anything Locally',
        subtitle: 'बैतूल का अपना OLX',
        gradient: ['#7B1FA2', '#9C27B0'],
        emoji: '💰',
    },
];
